version: 1.0.{build}
configuration: Release
before_build:
- nuget restore ".\GreatFriends.ThaiBahtText.sln"
build:
  project: .\GreatFriends.ThaiBahtText.sln
  verbosity: minimal
artifacts:
- path: GreatFriends.ThaiBahtText\bin\Release\ThaiBahtText.dll
  name: DLL File
